$SERVER = "fbelfortS"
$SERVER_WORKER = "fbelfortSW"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12"
  config.vm.box_version = "202407.22.0"
 
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end
  config.vm.define $SERVER do |server|
    server.vm.hostname = $SERVER
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.provision "shell", path: "./scripts/server_setup.sh"
  end
  config.vm.define $SERVER_WORKER do |serverWorker|
    serverWorker.vm.hostname = $SERVER_WORKER
    serverWorker.vm.network :private_network, ip: "192.168.56.111"
    serverWorker.vm.provision "shell", path: "./scripts/worker_setup.sh"
  end
end
